add_newline = false

[aws]
symbol = "îŒ½  "

[git_branch]
symbol = "ï˜ "

[git_commit]
tag_symbol = ' ï’ '

[memory_usage]
symbol = "ó°› "

[package]
disabled = true

[python]
format = "via [${symbol}${pyenv_prefix}(${version} )]($style)"
symbol = "îˆµ "
style = "bold blue"
python_binary = [".venv/bin/python", ".venv/Scripts/python"]

[kotlin]
disabled = true

[custom.kotlin_gradle]
command = "open gradle/libs.versions.toml | get versions.kotlin"
format = "via [${symbol}(v$output )]($style)"
symbol = "ğŸ…º "  
style = "bold blue"
shell = ["nu"]
detect_folders = [".kotlin"]

