[helpers]

[default]
depends = []

[default.files]
mpv = "~/scoop/persist/mpv/portable_config/"
nushell = "~/AppData/Roaming/nushell/"
nvim = "~/AppData/Local/nvim/"
starship = "~/.config/"
wezterm = "~"

[default.variables]

[settings]
default_target_type = "automatic"
