[helpers]

[default]
depends = []

[default.files]
mpv = "~/scoop/persist/mpv/portable_config/"
nushell = "~/AppData/Roaming/nushell/"
nvim = "~/AppData/Local/nvim/"
pgcli = "~/AppData/Local/dbcli/pgcli/"
starship = "~/.config/"
wezterm = "~"
yazi = "~/AppData/Roaming/yazi/config/"

[default.variables]

[settings]
default_target_type = "automatic"
